//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `CaseOffice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CaseOffice;

/**
 * Helper class for marshaling/unmarshaling CaseResults.
 **/
public final class CaseResultsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, CaseResult[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                CaseResult.ice_write(ostr, v[i0]);
            }
        }
    }

    public static CaseResult[] read(com.zeroc.Ice.InputStream istr)
    {
        final CaseResult[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new CaseResult[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = CaseResult.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CaseResult[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, CaseResult[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CaseResultsHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<CaseResult[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            CaseResult[] v;
            v = CaseResultsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
