//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `CaseOffice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CaseOffice;

public enum CaseType implements java.io.Serializable
{
    ConstructionPermission(0),
    DrivingLicense(1),
    PassportRequest(2);

    public int value()
    {
        return _value;
    }

    public static CaseType valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return ConstructionPermission;
        case 1:
            return DrivingLicense;
        case 2:
            return PassportRequest;
        }
        return null;
    }

    private CaseType(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 2);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, CaseType v)
    {
        if(v == null)
        {
            ostr.writeEnum(CaseOffice.CaseType.ConstructionPermission.value(), 2);
        }
        else
        {
            ostr.writeEnum(v.value(), 2);
        }
    }

    public static CaseType ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(2);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CaseType> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CaseType v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<CaseType> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static CaseType validate(int v)
    {
        final CaseType e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
