//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `CaseOffice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CaseOffice;

public interface OfficePrx extends com.zeroc.Ice.ObjectPrx
{
    default CaseAck makeCaseRequest(CaseRequest caseRequest)
    {
        return makeCaseRequest(caseRequest, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CaseAck makeCaseRequest(CaseRequest caseRequest, java.util.Map<String, String> context)
    {
        return _iceI_makeCaseRequestAsync(caseRequest, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CaseAck> makeCaseRequestAsync(CaseRequest caseRequest)
    {
        return _iceI_makeCaseRequestAsync(caseRequest, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CaseAck> makeCaseRequestAsync(CaseRequest caseRequest, java.util.Map<String, String> context)
    {
        return _iceI_makeCaseRequestAsync(caseRequest, context, false);
    }

    /**
     * @hidden
     * @param iceP_caseRequest -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CaseAck> _iceI_makeCaseRequestAsync(CaseRequest iceP_caseRequest, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CaseAck> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "makeCaseRequest", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     CaseRequest.ice_write(ostr, iceP_caseRequest);
                 }, istr -> {
                     CaseAck ret;
                     ret = CaseAck.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void checkCaseResults(String applicantID, ApplicantPrx applicant)
    {
        checkCaseResults(applicantID, applicant, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void checkCaseResults(String applicantID, ApplicantPrx applicant, java.util.Map<String, String> context)
    {
        _iceI_checkCaseResultsAsync(applicantID, applicant, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> checkCaseResultsAsync(String applicantID, ApplicantPrx applicant)
    {
        return _iceI_checkCaseResultsAsync(applicantID, applicant, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> checkCaseResultsAsync(String applicantID, ApplicantPrx applicant, java.util.Map<String, String> context)
    {
        return _iceI_checkCaseResultsAsync(applicantID, applicant, context, false);
    }

    /**
     * @hidden
     * @param iceP_applicantID -
     * @param iceP_applicant -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_checkCaseResultsAsync(String iceP_applicantID, ApplicantPrx iceP_applicant, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "checkCaseResults", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_applicantID);
                     ostr.writeProxy(iceP_applicant);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static OfficePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static OfficePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, OfficePrx.class, _OfficePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default OfficePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (OfficePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default OfficePrx ice_adapterId(String newAdapterId)
    {
        return (OfficePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default OfficePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (OfficePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default OfficePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (OfficePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default OfficePrx ice_invocationTimeout(int newTimeout)
    {
        return (OfficePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default OfficePrx ice_connectionCached(boolean newCache)
    {
        return (OfficePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default OfficePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (OfficePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficePrx ice_secure(boolean b)
    {
        return (OfficePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default OfficePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (OfficePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficePrx ice_preferSecure(boolean b)
    {
        return (OfficePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default OfficePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (OfficePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default OfficePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (OfficePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default OfficePrx ice_collocationOptimized(boolean b)
    {
        return (OfficePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default OfficePrx ice_twoway()
    {
        return (OfficePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default OfficePrx ice_oneway()
    {
        return (OfficePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default OfficePrx ice_batchOneway()
    {
        return (OfficePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default OfficePrx ice_datagram()
    {
        return (OfficePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default OfficePrx ice_batchDatagram()
    {
        return (OfficePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default OfficePrx ice_compress(boolean co)
    {
        return (OfficePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default OfficePrx ice_timeout(int t)
    {
        return (OfficePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default OfficePrx ice_connectionId(String connectionId)
    {
        return (OfficePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default OfficePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (OfficePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::CaseOffice::Office";
    }
}
